DevCamp-TeamSparta/QAing-FE

src/components/atoms/OAuthButton/index.tsx
src/components/organisms/SignupOrganism/index.tsx
src/services/auth/google.api.ts

Feat: axios요청로직 button이동

---

src/app/auth/google/callback/page.tsx

Feat: js-cookie 쿠기 사용

---

src/app/auth/google/callback/page.tsx

Doc: 쿠키값 콘솔로그 추가

---

src/components/atoms/OAuthButton/index.tsx

Doc: 구글로그인 테스트

---

.env
src/app/auth/google/callback/page.tsx
src/utils/httpClient.ts

- httpClient withCredentials true추가

Feat: baseurl 변경

---

src/app/auth/google/callback/page.tsx
src/utils/httpClient.ts

Dcos: access-token이 불러오지 않는문제

---

src/app/auth/google/callback/page.tsx

- console.log res.data
- console.log JSON.parse(res.data)

Feat: api test response.data 값 확인

---

src/app/auth/google/callback/page.tsx

Docs: 응답 확인

---

src/app/auth/google/callback/page.tsx

- UpdateUserDto 객체 사용 users/profile에 put 요청

Docs: api test put users/profile

---

src/app/auth/google/callback/page.tsx

Docs: API test 메인페이지 / 폴더명 수정

---

src/app/auth/google/callback/page.tsx

Feat.folder details

---

src/app/auth/google/callback/page.tsx

Docs: API test 메인페이지 / 폴더 삭제

---

src/app/auth/google/callback/page.tsx

Docs: API test

---

src/app/auth/google/callback/page.tsx
src/components/templetes/FolderTempletes/Folder.tsx

Dcos: API test

---

src/app/auth/google/callback/page.tsx

- 영상 저장이 안되어 있는 이슈 발생
- 새로운 영상의 폴더의 이슈로 다시 테스트

Dcos: 폴더페이지 / 이슈명 수정

---

src/components/templetes/FolderTempletes/Folder.tsx

- 테스트 시나리오
- 영상 저장 후 QAing 페이지로 이동
- 페이지 이동 후 get요청, 데이터가 들어오기 전 까지 로딩중 메세지가 나타남
- 데이터가 들어오면 랜더링된다.

Feat: 디테일 페이지 API 요청테스트

---

src/components/templetes/FolderTempletes/Folder.tsx

Docs: 디테일 페이지 API 요청테스트2

---

src/components/templetes/FolderTempletes/Folder.tsx

- isLoading을 사이드 이팩트로 관리
- useEffect에 setLoading을 추가

Docs:  디테일 페이지 API 요청테스트3

---

src/components/templetes/FolderTempletes/Folder.tsx

Docs: 디테일 페이지 API 요청테스트4

---

src/components/templetes/FolderTempletes/Folder.tsx

Docs: 디테일 페이지 API 요청테스트5

---

src/app/auth/google/callback/page.tsx
src/components/atoms/OAuthButtonAtoms/index.tsx
src/components/molcules/TableMolecules/index.tsx
src/components/templetes/FolderTempletes/Folder.tsx
src/components/templetes/SignupTempletes/GoogleSignup.tsx
src/services/auth/google.api.ts

Docs: 익스텐션 제출전 코드수정

---

src/app/auth/google/callback/page.tsx
src/app/home/page.tsx
src/components/templetes/SignupTempletes/GoogleSignup.tsx

- 레코드의 영상을 서버로 보내는 로직이 app.qaing에서만 동작하므로 녹화시작 버튼을 누르면 app.qaing.co/home 으로 이동 하도록 함

Docs: home페이지 추가

---

src/components/templetes/FolderTempletes/Folder.tsx

- folder ? 에서 folder.length !==0 으로 로직 변경

Docs: folder가 빈배열일 때 파일을 저장하고 있다는 문구 보여주기

---

src/components/templetes/FolderTempletes/Folder.tsx
src/components/templetes/LoginTempletes/Login.tsx
src/components/templetes/SignupTempletes/GoogleSignup.tsx
src/utils/httpClient.ts

Feat: SSE test

---

src/app/auth/google/callback/page.tsx
src/components/atoms/OAuthButtonAtoms/index.tsx
src/components/templetes/LoginTempletes/Login.tsx

- PUBLIC_BACKEND_API_URL
- PUBLIC_FRONTEND_URL

Docs: 환경변수명 변경

---

src/components/templetes/FolderTempletes/Folder.tsx

Docs: sse 수신 성공

---

src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/organisms/MainPageOrganism/VideoTableBody.tsx
src/states/issue-store.ts
src/types/userFolder.types.ts

Feat: API test

---

src/components/organisms/MainPageOrganism/VideoTable.tsx

Feat: VideoTable 컴포넌트

---

src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/templetes/(sidebar)/MainPage/MainPage.tsx

Feat: get요청 컴포넌트 위치이동

---

src/components/organisms/MainPageOrganism/DeleteFolderModal.tsx
src/components/organisms/MainPageOrganism/VideoTableBody.tsx

- ()=> onClickDeleteButtonHandler(folderId)

Feat: 삭제버튼 onclick이벤트 내부 로직변경

---

src/services/folder/folder.api.ts

Docs: endpoint 오타수정

---

src/app/globals.css
src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/organisms/MainPageOrganism/VideoTableBody.tsx
tailwind.config.ts

Feat: 폴더명 변경 기능 구현

---

src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/organisms/MainPageOrganism/VideoTableBody.tsx
src/types/userFolder.types.ts

- 기존 createdAt에서 데이터를 가공해서 사용 하던 것을 folderName데이터를 받아오는 것으로 변경

Feat: folderName 파싱

---

src/app/globals.css
src/components/organisms/MainPageOrganism/DeleteFolderModal.tsx
src/components/organisms/MainPageOrganism/InstallBanner.tsx
src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/organisms/MainPageOrganism/VideoTableBody.tsx
src/components/organisms/layout/SideBar.tsx
src/components/templetes/(sidebar)/MainPage/MainPage.tsx
src/services/folder/folder.api.ts
src/services/instance.ts
src/types/userFolder.types.ts
tailwind.config.ts

메인페이지 폴더 가져오기, 수정, 삭제기능 구현

---

src/components/organisms/MainPageOrganism/DeleteFolderModal.tsx
src/components/organisms/layout/SideBar.tsx

Feat: 삭제기능 test

---

src/components/organisms/IssuePageOrganisms/DeleteIssueModal.tsx
src/components/organisms/IssuePageOrganisms/issueCardOrganism/index.tsx

- DeleteIssueModal 내 이슈 삭제 기능 테스트예정

Feat: 이슈 삭제기능 test

---

src/app/auth/login/page.tsx
src/app/globals.css
src/components/atoms/common/ProgressBar.tsx
src/components/organisms/IssuePageOrganisms/IssueEmptyOrganism.tsx
src/components/organisms/IssuePageOrganisms/LoadingIssueModal.tsx
src/components/organisms/modal/ModalPortal.tsx
src/components/templetes/FolderTempletes/Folder.tsx
src/states/modalStore.ts

Feat/progress conflict 해결

---

src/components/organisms/IssuePageOrganisms/IssueEmptyOrganism.tsx

Docs: 의존성배열에 folderName추가

---

src/components/organisms/IssuePageOrganisms/IssueEmptyOrganism.tsx

Docs: sse 수신

---

src/components/organisms/IssuePageOrganisms/IssueModalOrganism/index.tsx

- justify-center 추가 px 60 -> 30

Docs: image tage fill 추가

---

src/app/folders/[id]/issues/page.tsx
src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/templetes/FolderTemplete.tsx
src/components/templetes/IssuePageTemplete/IssueTemplete.tsx

- 파일명 foldertemplete -> issuetemplete로 변경

Feat: 이슈페이지 미 로그인시 로그인 페이지로 이동

---

README.md
src/app/auth/login/page.tsx
src/components/organisms/MainPageOrganism/VideoTable.tsx
src/components/templetes/IssuePageTemplete/IssueTemplete.tsx

- test.app.qaing/auth/login -> auth/login

Docs: main페이지 미로그인시 로그인페이지 이동 주소 변경

---

src/components/organisms/MainPageOrganism/VideoTable.tsx

Docs: VideoTable 코드 수정

---

src/components/organisms/IssuePageOrganisms/IssueEmptyOrganism.tsx

- pre-progress
- progress
- done

Docs: sse test 3단계

---

package-lock.json
package.json
src/app/auth/google/callback/page.tsx
src/components/atoms/OAuthButtonAtom/OAuthButtonAtom.tsx
src/components/organisms/IssuePageOrganisms/IssueCardOrganism/IssueCardOrganism.tsx
src/components/organisms/IssuePageOrganisms/IssueModalOrganism/IssueModalOrganism.tsx
src/components/organisms/MainPageOrganism/FolderTableBody.tsx
src/components/organisms/MainPageOrganism/InstallBanner.tsx
src/components/organisms/SignupOrganism/GoogleSignnupOrgansim.tsx
src/components/organisms/layoutOrganism/SideBar.tsx
src/components/templetes/(sidebar)/MainPageTemplete/MainPageTemplete.tsx
src/components/templetes/AuthTemplete/OnboardingTemplete.tsx
src/components/templetes/IssuePageTemplete/IssueTemplete.tsx
src/lib/amplitude.ts

- 모든페이지 amplitude 삽입
- 로그인페이지 SignupTeamplete, OAuthButtonAtom
- 메인페이지 MainPageTemPlete InstallBanner SideBar FolderTableBody
- 폴더페이지 IssueTemplete IssueCardOrganism 
등

Feat: amplitude test

---

src/app/auth/google/callback/page.tsx

Docs: 로그아웃 기능 test

---

src/components/organisms/MainPageOrganism/FolderTable.tsx

- status 401 코드에 return 추가 후 테스트

Docs: 로그인을 안했을 때 404페이지로 이동하는 현상

---

src/components/templetes/AuthTemplete/OnboardingTemplete.tsx

- 이미 사전정보를 등록한유저->메인페이지
- 비 로그인 유저->메인페이지
- 사전정보를 등록하지 않은 유저->리다이렉트x

Docs: 사전정보페이지 리다이렉트

---

src/components/templetes/AuthTemplete/OnboardingTemplete.tsx

Docs: 비로그인 유저 로직

---

src/components/organisms/layoutOrganism/ProfileModal.tsx
src/services/auth/auth.api.ts

- 오타 filname->filename
- filetype->type

Docs: api data key값변경

---

src/services/auth/auth.api.ts

- axios 요청으로 변경, withCredentials 제거

Docs: uploadImageToS3

---

src/app/auth/google/callback/page.tsx
src/components/organisms/GoogleSignnupOrgansim/GoogleSignnupOrgansim.tsx
src/components/organisms/layoutOrganism/ProfileModal.tsx
src/services/auth/auth.api.ts

- 1번 : 프로사진필만 바뀌는지
- 2번 : 프로필명만 바뀌는지
- 3번 : 프로필사진 이름 둘다 바뀌는지

Feat: 프로필명 이름수정 동시에 되는지 테스트

---

src/components/organisms/layoutOrganism/ProfileModal.tsx

사진만 변경되게 해야될지 아얘변경되지 않게 해야될지 고민중
- 프로필사진을 같은 사진으로 변경했을 때 사진전송이 되지 않게 할지 고민

Docs: 프로필사진은 변경햇는데 이름을 아무것도 입력안했을 때

---

src/components/atoms/issueThumbnailAtom/issueThumbnailAtom.tsx
src/components/organisms/IssuePageOrganisms/IssueModalOrganism/TestIssueModalOrganism.tsx

Docs: 미리보기 페이지 test

---

src/components/organisms/IssuePageOrganisms/DeleteIssueModal.tsx

Docs: 이슈 삭제 form추가 test

---

src/components/organisms/layoutOrganism/ProfileModal.tsx

Docs: 로그아웃 onSubmit -> onClick로 변경

---

src/app/auth/google/callback/page.tsx
src/app/layout.tsx

Feat: 채널톡 추가
